package se.fk.mimer.datamodel.v2.produceratresultat.intyg;

public enum IVIntygstyp
{
    E109,
    E121,
    DA1,
    INTYGFORSTUDENTER5166,
    INTYGVIDARBETEIANNATLAND5164,
    EUKORT,
    PROVISORISKTINTYG,
    E106,
    INTYGOMRATTTILLFORMANER,
    E108,
    SPANIENPENSIONARSINTYG13050,
    FORHANDSTILLSTAND

}
