// set 'group' for all modules/projects from gradle.properties
// Temporary disabled because of current CI validations
//allprojects {
//    group = providers.gradleProperty( "group" ).get()
//}

// root group and root version below is temporary fixes for pipeline validation
group = "se.fk.mimer"
version = "0.0.0"

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'jacoco'

    java {
        withJavadocJar()
        withSourcesJar()
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    // If a module has a 'jandex' task, make sure javadoc runs after it.
    // Fixes Gradle task validation (javadoc uses outputs touched by jandex).
    tasks.matching{ it.name == 'javadoc' }.configureEach {
        if (tasks.findByName( 'jandex' ) != null) {
            dependsOn(tasks.named('jandex'))
        }
    }

    // Apply to both main + test
    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    // Apply only to main
    tasks.withType(JavaCompile).matching { it.name == 'compileJava' }.configureEach {
        // Compiler flags (javac)
        def args = []
        args += '-Xlint:all'

        // Turn off warning for missing annotation processors. This warning assumes that every
        // annotation will be processed by an annotation processor, which is a false assumption.
        // Things like jakarta.ws.rs.Path annotations etc. are not, and are not meant to be,
        // processed by an annotation processor.
        args += '-Xlint:-processing'

        // Warnings as errors
        args += '-Werror'

        // Store method parameter names in bytecode (useful for reflection/frameworks)
        args += '-parameters'

        options.compilerArgs += args
    }

    test {
        useJUnitPlatform()
        //TODO: why do we have app.url, what is it used for and should we keep it?
        systemProperty "app.url", System.getProperty("app.url")
        testLogging { events "passed", "skipped", "failed" }
        finalizedBy jacocoTestReport

        jacoco {
            excludeClassLoaders = ["*QuarkusClassLoader"]
            destinationFile = layout.buildDirectory.file("jacoco/test.exec").get().asFile
        }
    }

    jacocoTestReport {
        dependsOn test
        reports {
            xml.required.set(true)
            html.required.set(false)
        }
    }

}