group=se.fk.mimer
version=0.2.2

# Enbart för akut-rättningar
#artifact.legacy.version=2.0.3

# Maven-publish + Gradle 6+ produces sha256/512 im maven-metadata.xml.
# This does not play nicely with java.repo.sfa.se. Turn off SHA-generation:
systemProp.org.gradle.internal.publish.checksums.insecure=true
# Global properties to be sent through CLI to overwrite values for uploading to nexus
uploadUser="USER"
uploadPassword="PASSWORD"

# Nexus
downloadURL=https://java.repo.sfa.se/repository/java-all
uploadURLSnapshots=https://java.repo.sfa.se/repository/Snapshots/
uploadURLReleases=https://java.repo.sfa.se/repository/Releases/
