# This file is used by the fk-cid-generic-sonarqube task in tekton

# These properties will be overridden by SONAR_ARGS.
sonar.projectName=mimer-datamodels

sonar.language=java
sonar.forceAnalysis=true
sonar.forceAuthentication=true

sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=**/build/reports/jacoco/test/jacocoTestReport.xml

# 1) Analyze everything except:
sonar.exclusions=\
  **/build/**,\
  **/META-INF/**,\
  **/src/test/**,\
  **/models-v2/src/main/java/se/fk/mimer/datamodel/v2/**

# Re-include what we want coverage on
sonar.inclusions=\
  **/models-v2/src/main/java/se/fk/mimer/datamodel/v2/handlaggning/**,\
  **/models-v2/src/main/java/se/fk/mimer/datamodel/v2/yrkande/**

# Ignore coverage for specific codec classes
sonar.coverage.exclusions=\
  **/codec-v2/src/main/java/se/fk/mimer/codec/v2/exceptions/**,\
  **/codec-v2/src/main/java/se/fk/mimer/codec/v2/jsonld/JsonLdEnvelopeBuilder.java**,\
  **/codec-v2/src/main/java/se/fk/mimer/codec/v2/jsonld/DataPayloadInspector.java**,\
  **/codec-v2/src/main/java/se/fk/mimer/codec/v2/jsonld/JsonLdExtractor.java**,\
  **/codec-v2/src/main/java/se/fk/mimer/codec/v2/payload/PayloadFormatValidator.java**,\
  **/codec-v2/src/main/java/se/fk/mimer/codec/v2/payload/PayloadParser.java**,\
  **/codec-v2/src/main/java/se/fk/mimer/codec/v2/payload/Base64UrlCodec.java**,\
  **/codec-v2/src/main/java/se/fk/mimer/codec/v2/registry/DefaultTypeRegistry.java**,\
  **/codec-v2/src/main/java/se/fk/mimer/codec/v2/registry/RegistryValidator.java**,\
  **/codec-v2/src/main/java/se/fk/mimer/codec/v2/registry/DefaultVariantRegistry.java**,\
  **/codec-v2/src/main/java/se/fk/mimer/codec/v2/jackson/polymorphism/VariantBasedDeserializer.java**,\
  **/codec-v2/src/main/java/se/fk/mimer/codec/v2/jackson/polymorphism/VariantInjectingDelegatingSerializer.java**,\
  **/codec-v2/src/main/java/se/fk/mimer/codec/v2/validation/DataleveransContractValidator.java**,\
  **/codec-v2/src/main/java/se/fk/mimer/codec/v2/api/MimerCodec.java**
  

sonar.qualitygate.wait=true

# Ignore sonarqube warning to use `var` in variable declarations/definitions
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=java:S6212
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.java

sonar.java.binaries=**/build/classes/java/main
sonar.java.test.binaries=**/build/classes/java/test