# This file is used by the fk-cid-generic-sonarqube task in tekton

# These properties will be overridden by SONAR_ARGS.
sonar.projectName=mimer-datamodels

sonar.language=java
sonar.forceAnalysis=true
sonar.forceAuthentication=true

sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=**/build/reports/jacoco/test/jacocoTestReport.xml
sonar.exclusions=**/build/**,**/test/**,**/META-INF/**,**/producermodels/*.java

sonar.qualitygate.wait=true

# Ignore sonarqube warning to use `var` in variable declarations/definitions
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=java:S6212
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.java

sonar.java.binaries=**/build/classes/java/main
sonar.java.test.binaries=**/build/classes/java/test