# This file is used by the fk-cid-generic-sonarqube task in tekton

# These properties will be overridden by SONAR_ARGS.
sonar.projectName=mimer-datamodels

sonar.language=java
sonar.forceAnalysis=true
sonar.forceAuthentication=true

sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=**/build/reports/jacoco/test/jacocoTestReport.xml

# 1) Analyze everything except:
sonar.exclusions=\
  **/build/**,\
  **/META-INF/**,\
  **/src/test/**,\
  **/models-v1/src/main/java/se/fk/mimer/datamodel/v1/**

# Re-include what we want coverage on
sonar.inclusions=\
  **/models-v1/src/main/java/se/fk/mimer/datamodel/v1/handlaggning/**,\
  **/models-v1/src/main/java/se/fk/mimer/datamodel/v1/yrkande/**

# Ignore coverage for specific codec classes
sonar.coverage.exclusions=\
  **/codec-v1/src/main/java/se/fk/mimer/codec/v1/exceptions/**,\
  **/codec-v1/src/main/java/se/fk/mimer/codec/v1/jsonld/JsonLdEnvelopeBuilder.java**,\
  **/codec-v1/src/main/java/se/fk/mimer/codec/v1/jsonld/DataPayloadInspector.java**,\
  **/codec-v1/src/main/java/se/fk/mimer/codec/v1/jsonld/JsonLdExtractor.java**,\
  **/codec-v1/src/main/java/se/fk/mimer/codec/v1/payload/PayloadFormatValidator.java**,\
  **/codec-v1/src/main/java/se/fk/mimer/codec/v1/payload/PayloadParser.java**,\
  **/codec-v1/src/main/java/se/fk/mimer/codec/v1/payload/Base64UrlCodec.java**,\
  **/codec-v1/src/main/java/se/fk/mimer/codec/v1/registry/DefaultTypeRegistry.java**,\
  **/codec-v1/src/main/java/se/fk/mimer/codec/v1/registry/RegistryValidator.java**,\
  **/codec-v1/src/main/java/se/fk/mimer/codec/v1/registry/DefaultVariantRegistry.java**,\
  **/codec-v1/src/main/java/se/fk/mimer/codec/v1/jackson/polymorphism/VariantBasedDeserializer.java**,\
  **/codec-v1/src/main/java/se/fk/mimer/codec/v1/jackson/polymorphism/VariantInjectingDelegatingSerializer.java**,\
  **/codec-v1/src/main/java/se/fk/mimer/codec/v1/validation/DataleveransContractValidator.java**,\
  **/codec-v1/src/main/java/se/fk/mimer/codec/v1/api/MimerCodec.java**
  

sonar.qualitygate.wait=true

# Ignore sonarqube warning to use `var` in variable declarations/definitions
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=java:S6212
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.java

sonar.java.binaries=**/build/classes/java/main
sonar.java.test.binaries=**/build/classes/java/test