plugins {
    alias libs.plugins.jandex
    // TODO: is groovy necessary?, i will paste earlier comment below:
    // Apply the groovy plugin to also add support for Groovy (needed for Spock)
    id 'groovy'
    // Adds the 'publish' task which is used to push to java.repo
    id 'maven-publish'
}

version = providers.gradleProperty( 'artifact.legacy.version' ).get()

jar {
    manifest {
        attributes 'Implementation-Version': project.version.toString()
    }
}

dependencies {
    implementation libs.jakartaee.api
    implementation libs.jackson.databind
    implementation libs.jackson.datatype
    implementation libs.jackson.core
    implementation libs.jackson.jdk8
    implementation libs.java.uuid.generator
    implementation libs.mimer.utils

    compileOnly libs.lombok
    annotationProcessor( libs.lombok )
    testCompileOnly libs.lombok
    testAnnotationProcessor( libs.lombok )

    testImplementation platform( libs.junit.bom )
    testImplementation libs.junit.jupiter

    testImplementation libs.hibernate.validator
    testImplementation libs.glassfish.expressly
    testImplementation platform( libs.mockito.bom )
    testImplementation libs.mockito
}

publishing {
    publications {
        lib(MavenPublication) {
            artifactId = 'mimer-datamodels'
            from components.java
        }
    }

    repositories {
        maven {
            url = uploadURLReleases
            credentials {
                username uploadUser
                password uploadPassword
            }
        }
    }
}