package se.fk.mimer.datamodel.v1.beslut;

public enum BeslutandeOrganisation
{
    FORSAKRINGSKASSAN,
    FORVALTNINGSRATTEN,
    KAMMARRATTEN,
    HOGSTA_FORVALTNINGSDOMSTOLEN,
    MIGRATIONSVERKET,
    ARBETSFORMEDLINGEN,
    TINGSRATTEN,
    SKATTEVERKET;
}
