package se.fk.mimer.producermodels.bidragssparr;

public enum GrundForBeslut
{
    ORIKTIGA_UPPGIFTER,
    UNDERLATIT_SIG_ANMALNINGSSKYLDIGHET,
    VARKEN_ORIKTIGA_UPPGIFTER_ELLER_UNDERLATIT_SIG_ANMALNINGSSKYLDIGHET
}
