plugins {
    alias libs.plugins.jandex
    id 'maven-publish'
}

group = "se.fk.mimer.models"
version = providers.gradleProperty( 'artifact.v1.version' ).get()

jar {
    manifest {
        attributes 'Implementation-Version': project.version.toString()
    }
}

dependencies {
    implementation libs.jakartaee.api
    implementation libs.jackson.databind
    implementation libs.jackson.datatype
    implementation libs.jackson.core
    implementation libs.jackson.jdk8
    implementation libs.java.uuid.generator

    compileOnly libs.lombok
    annotationProcessor( libs.lombok )
    testCompileOnly libs.lombok
    testAnnotationProcessor( libs.lombok )

    testImplementation platform( libs.junit.bom )
    testImplementation libs.junit.jupiter

    testImplementation libs.hibernate.validator
    testImplementation libs.glassfish.expressly
    testImplementation platform( libs.mockito.bom )
    testImplementation libs.mockito
}

publishing {
    publications {
        lib(MavenPublication) {
            artifactId = 'models-v1'
            from components.java
        }
    }

    repositories {
        maven {
            url = uploadURLReleases
            credentials {
                username uploadUser
                password uploadPassword
            }
        }
    }
}