plugins {
    // Empty for now
}

group = "se.fk.mimer"
version = providers.gradleProperty( 'artifact.v2.version' ).get()

jar {
    manifest {
        attributes 'Implementation-Version': project.version.toString()
    }
}

dependencies {
    implementation(project(":models-v2"))

    implementation libs.jakartaee.api
    implementation libs.jackson.databind
    implementation libs.jackson.datatype
    implementation libs.jackson.jdk8

    compileOnly libs.lombok
    annotationProcessor( libs.lombok )
    testCompileOnly libs.lombok
    testAnnotationProcessor( libs.lombok )

    testImplementation(libs.hibernate.validator)
    testImplementation(libs.glassfish.expressly)
    testImplementation platform( libs.junit.bom )
    testImplementation libs.junit.jupiter
}

tasks.test {
    systemProperty("codec.debugJson", System.getProperty( "codec.debugJson", "false" ))
    testLogging { showStandardStreams = true }
}

// todo add publication