plugins {
    id 'maven-publish'
}

group = "se.fk.mimer.codecs"
version = providers.gradleProperty( 'artifact.v1.version' ).get()

jar {
    manifest {
        attributes 'Implementation-Version': project.version.toString()
    }
}

dependencies {
    implementation(project(":models-v1"))

    compileOnly libs.jakartaee.api
    implementation libs.jackson.databind
    implementation libs.jackson.datatype
    implementation libs.jackson.jdk8

    implementation libs.hibernate.validator
    runtimeOnly libs.glassfish.expressly

    compileOnly libs.lombok
    annotationProcessor( libs.lombok )
    testCompileOnly libs.lombok
    testAnnotationProcessor( libs.lombok )

    testImplementation platform( libs.junit.bom )
    testImplementation libs.junit.jupiter
}

tasks.test {
    systemProperty("codec.debugJson", System.getProperty( "codec.debugJson", "false" ))
    testLogging { showStandardStreams = true }
}

publishing {
    publications {
        lib(MavenPublication) {
            artifactId = 'codec-v1'
            from components.java
        }
    }

    repositories {
        maven {
            url = uploadURLReleases
            credentials {
                username uploadUser
                password uploadPassword
            }
        }
    }
}